trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core 3.1
  inputs:
    packageType: sdk
    version: 3.1.101
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects:  '**/*.csproj'
    arguments: '--filter TestCategory=UnitTest'

- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: 19.03.3
    releaseType: stable

- task: Bash@3
  displayName: Start and Initialize Postgres Container
  inputs:
    targetType: 'inline'
    script: './AuthSystem.Scripts/initialize_postgres.sh'

- task: DotNetCoreCLI@2
  displayName: Database Integration Tests
  inputs:
    command: test
    projects: **/*.csproj'
    arguments: '--filter TestCategory=IntegrationTest&TestCategory=DbTest'

- task: DotNetCoreCLI@2
  displayName: Web Integration Tests
  inputs:
    command: test
    projects: **/*.csproj'
    arguments: '--filter TestCategory=IntegrationTest&TestCategory=WebTest'